In [1]:
import numpy as np

In [2]:
l = [0,1,2,3,4,5,6,7,8]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
matrix = np.array(l).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
matrix.mean(axis = 0)  #axis = 0 => column

array([3., 4., 5.])

In [5]:
matrix.mean(axis = 1) #axis = 1 => row

array([1., 4., 7.])

In [6]:
matrix.flatten().mean()

4.0

In [7]:
m = [matrix.mean(axis = 0),matrix.mean(axis = 1),matrix.flatten().mean()]
m

[array([3., 4., 5.]), array([1., 4., 7.]), 4.0]

In [8]:
m = [(matrix.mean(axis = 0)).tolist(),(matrix.mean(axis = 1)).tolist(),matrix.flatten().mean()]
m

[[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]

In [9]:
matrix.var(axis = 0)

array([6., 6., 6.])

In [10]:
matrix.var(axis = 1)

array([0.66666667, 0.66666667, 0.66666667])

In [11]:
matrix.flatten().var()

6.666666666666667

In [12]:
v = [(matrix.var(axis = 0)).tolist(),(matrix.var(axis = 1)).tolist(),matrix.flatten().var()]
v

[[6.0, 6.0, 6.0],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 6.666666666666667]

In [13]:
matrix.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [14]:
matrix.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

In [15]:
matrix.flatten().std()

2.581988897471611

In [16]:
s = [(matrix.std(axis = 0)).tolist(),(matrix.std(axis = 1)).tolist(),matrix.flatten().std()]
s

[[2.449489742783178, 2.449489742783178, 2.449489742783178],
 [0.816496580927726, 0.816496580927726, 0.816496580927726],
 2.581988897471611]

In [17]:
matrix.max(axis = 0)

array([6, 7, 8])

In [18]:
matrix.max(axis = 1)

array([2, 5, 8])

In [19]:
matrix.flatten().max()

8

In [20]:
big = [(matrix.max(axis = 0)).tolist(),(matrix.max(axis = 1)).tolist(),matrix.flatten().max()]
big

[[6, 7, 8], [2, 5, 8], 8]

In [21]:
matrix.min(axis = 0)

array([0, 1, 2])

In [22]:
matrix.min(axis = 1)

array([0, 3, 6])

In [23]:
matrix.flatten().min()

0

In [24]:
small = [(matrix.min(axis = 0)).tolist(),(matrix.min(axis = 1)).tolist(),matrix.flatten().min()]
small

[[0, 1, 2], [0, 3, 6], 0]

In [25]:
matrix.sum(axis = 0)

array([ 9, 12, 15])

In [26]:
matrix.sum(axis = 1)

array([ 3, 12, 21])

In [27]:
matrix.flatten().sum()

36

In [28]:
add = [(matrix.sum(axis = 0)).tolist(),(matrix.sum(axis = 1)).tolist(),matrix.flatten().sum()]
add

[[9, 12, 15], [3, 12, 21], 36]

In [29]:
c ={
    'mean':                m,
    'variance':            v,
    'standard deviation':  s,
    'max':                 big,
    'min':                 small,
    'sum':                 add
}

c

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

In [30]:
print(c)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}
